version: "3.9"

services:
  roscore:
    container_name: roscore-master
    restart: "no"
    image: ghcr.io/pseusys/robair-pyified:main
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: roscore
    healthcheck:
      test: bash entrypoint.sh rostopic list
      interval: 5s
      timeout: 5s
      retries: 3

  roslaunch:
    container_name: roslaunch-executable
    restart: "no"
    image: ghcr.io/pseusys/robair-pyified:main
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - TARGET
    volumes:
      - ../${SOURCES}:/~/catkin_ws/src
    command: bash -c "catkin_make && python3 generate_launch_config.py $$TARGET > launch && roslaunch launch"
    healthcheck:
      test: test $(($(bash entrypoint.sh rosnode list | tr -cd '\n' | wc -c) - 2)) -eq $(echo $$TARGET | tr -cd '\n' | wc -c)
      interval: 5s
      timeout: 5s
      retries: 10

  rosbag:
    container_name: rosbag-simulation
    restart: always
    image: ghcr.io/pseusys/robair-pyified:main
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - RECORD
      - ROS_MASTER_URI=http://roscore:11311/
    volumes:
      - ../assets/data:/~/catkin_ws/data
    command: bash -c "rosbag play data/$$RECORD"
    depends_on:
      roscore:
        condition: service_healthy

  rviz:
    container_name: rviz-visualization
    restart: "no"
    image: ghcr.io/pseusys/robair-pyified:main
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - CONFIG
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority:ro
      - ../config:/~/catkin_ws/config
    devices:
      - /dev/dri:/dev/dri
    command: bash -c "rviz -d /~/catkin_ws/config/$$CONFIG 2> >(grep -v TF_REPEATED_DATA buffer_core)"
