version: "3.9"

services:
  roscore:
    extends:
      file: common-services.yml
      service: roscore

  roslaunch:
    extends:
      file: common-services.yml
      service: roslaunch
    environment:
      - ROS_MASTER_URI=http://roscore:11311/
    depends_on:
      roscore:
        condition: service_healthy

  rosbag:
    extends:
      file: common-services.yml
      service: rosbag

  rviz:
    extends:
      file: common-services.yml
      service: rviz
    environment:
      - ROS_MASTER_URI=http://roscore:11311/
    depends_on:
      roscore:
        condition: service_healthy
      roslaunch:
        condition: service_healthy

networks:
  default-network:
    driver: host
