version: "3.9"

services:
  roscore:
    extends:
      file: common-services.yml
      service: roscore

  roslaunch:
    extends:
      file: common-services.yml
      service: roslaunch
    environment:
      - ROS_MASTER_URI=http://roscore:11311/
    depends_on:
      roscore:
        condition: service_healthy

  rosbag:
    extends:
      file: common-services.yml
      service: rosbag

  rviz:
    extends:
      file: common-services.yml
      service: rviz
    environment:
      - CONFIG
      - ROS_MASTER_URI=http://roscore:11311/
    volumes:
      - ../config/${CONFIG}:/~/catkin_ws/config/${CONFIG}
    command: bash -c "rviz -d /~/catkin_ws/config/$$CONFIG 2> >(grep -v TF_REPEATED_DATA)"
    depends_on:
      roscore:
        condition: service_healthy
      roslaunch:
        condition: service_healthy

networks:
  default-network:
    driver: host
