version: "3.9"

services:
  roslaunch:
    extends:
      file: common-services.yml
      service: roslaunch
    environment:
      - ROS_IP=${ROBAIR_IP}
      - ROS_MASTER_URI=http://${ROBAIR_IP}:11311/

  rviz:
    extends:
      file: common-services.yml
      service: rviz
    environment:
      - ROS_IP=${ROBAIR_IP}
      - ROS_MASTER_URI=http://${ROBAIR_IP}:11311/
    depends_on:
      roslaunch:
        condition: service_healthy

networks:
  default-network:
    driver: host
