version: "3.9"

services:
  roslaunch:
    extends:
      file: common-services.yml
      service: roslaunch
    environment:
      - ROS_MASTER_URI=http://${ROBAIR_IP}:11311/

  rviz:
    extends:
      file: common-services.yml
      service: rviz
    environment:
      - CONFIG
      - ROS_MASTER_URI=http://${ROBAIR_IP}:11311/
    volumes:
      - ../config/${CONFIG}:/~/catkin_ws/config/${CONFIG}
    command: bash -c "rviz -d /~/catkin_ws/config/$$CONFIG 2> >(grep -v TF_REPEATED_DATA)"
    depends_on:
      roslaunch:
        condition: service_healthy

networks:
  default-network:
    driver: host
