version: "3.9"

services:
  roscore:
    extends:
      file: common-services.yml
      service: roscore

  rosrun:
    container_name: rosrun-executable
    restart: "no"
    image: ghcr.io/pseusys/robair-pyified/ros-gazebo:main
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: ros-gazebo
    environment:
      - ROS_MASTER_URI=http://roscore:11311/
    command: bash -c "catkin_make && rosrun gazebo_ros gzserver"
    depends_on:
      roscore:
        condition: service_healthy
    healthcheck:
      test: bash ./entrypoint.sh rosservice list
      interval: 5s
      timeout: 5s
      retries: 10

  rviz:
    extends:
      file: common-services.yml
      service: rviz
    environment:
      - ROS_MASTER_URI=http://roscore:11311/
    depends_on:
      roscore:
        condition: service_healthy

networks:
  default-network:
    driver: host
